# Generated by Django 4.2 on 2024-09-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehiclestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclestatus',
            options={'verbose_name_plural': 'Vehicle Status'},
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='status',
            field=models.CharField(blank=True, choices=[('in', 'In'), ('out', 'Out')], max_length=50, null=True),
        ),
    ]
