# Generated by Django 4.2 on 2024-09-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vehiclestatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='status',
            field=models.CharField(blank=True, choices=[('in', 'In'), ('out', 'Out')], default='out', max_length=50, null=True),
        ),
    ]
