# Generated by Django 4.2 on 2024-09-16 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_owner_profile_photo_alter_vehiclestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestatus',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_status', to='core.car'),
        ),
    ]
