# Generated by Django 4.2 on 2024-09-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vehiclestatus_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='core.vehiclestatus'),
        ),
    ]
