# Generated by Django 4.2 on 2024-09-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_vehiclestatus_car_car_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
